### ISSUE TITLE
Mcinfected Rank Permissions Bug

### ISSUE THREAD

**Issue by zvvx** [Bimmr/McInfected-Ranks#1]
Recently I have been testing around with McInfected Ranks plugin. I found that if you have another ranks/permissions plugin it will add the permissions from the McInfected Ranks to the persons other permissions file from the other rank plugin. The problem with this is that it only adds the permissions when you get to the next rank in McInfected Ranks, it doesn't remove the permissions from the rank the player used to have.
If you have any trouble understanding this tell me and I can try to explain it differently.

**Comment by Bimmr** [comment]
Just want to see if i got it, 

- Joins McInfected
- Gets Ranks Permissions
- Ranks up
- Get New Ranks Permissions
- Leaves McInfected
- Looses New Ranks Permissions

- Leaves Old Rank permissions

**Comment by zvvx** [comment]
No
* McInfected Ranks added
*Other permission/ranks added
*Joins McInfected
*Ranks up
*Still has same permissions as their old rank

**Comment by Bimmr** [comment]
K, I'll pm you a version in about 10 minutes that should fix it
