### ISSUE TITLE
Can not edit ranks

### ISSUE THREAD

**Issue by DarkRaider462** [Bimmr/McInfected-Ranks#4]
Whenever i change something in the config. As example a prefix for a certain rank.
The config resets itself every restart / reload of the plugin. It resets everything i made back to the Survivor etc. ranks.

**Comment by Bimmr** [comment]
That happens when you brake yaml, paste it into an online yaml parser and
fix what ever line gets you the error

**Comment by DarkRaider462** [comment]
I edited it through the .yml file, and that's why it didn't work. I simply changed 1 prefix, and it still reset, but i found out i can edit in-game. Sorry for disturbing, I should have looked there.
Amazing plugin :D
