### ISSUE TITLE
Not working on 1.10 spigot server

### ISSUE THREAD

**Issue by ericbarbwire** [Bimmr/McInfected-Ranks#8]
The plugin will not show on my plugin list. 
MCInfected-Ranks Version: v1.2.0
MCInfected Version: v1.4.3
MCInfected-Leaderboard Version: v0.1.0
BimmCore Version: v0.0.6

**Comment by ericbarbwire** [comment]
McInfected Version

**Comment by Bimmr** [comment]
"It's not working" Is not a useful issue description... 
Maybe give me the error that was shown in the console...
